//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepoDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> TotalCnt { get; set; }
        public int Status { get; set; }
    }
}
