//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepoDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingDetail
    {
        public int MeetingId { get; set; }
        public string MeetingSubject { get; set; }
        public string MeetingAttendees { get; set; }
        public string MeetingAgenda { get; set; }
        public System.DateTime MeetingDateTime { get; set; }
    }
}
